version: '3'

networks: 
  laravel:

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports: 
      - "7000:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel 
  mysql:
    image: mysql:5.7
    container_name: mysql_laravel
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: dan_payment
      MYSQL_USER: paymente-admin
      MYSQL_PASSWORD: pay178523
      MYSQL_ROOT_PASSWORD: pay178523
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel
    volumes: 
      - ./www:/var/www/html
    ports: 
      - "8082:80"
    networks: 
      - laravel
  composer:
    image: composer:latest
    container_name: composer_laravel
    volumes: 
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on: 
      - mysql
    ports: 
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: pay178523
    networks: 
      - laravel
  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_laravel
    volumes: 
      - ./www:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - laravel